const originalQuestions = [
    'Working with hands',
    'Solving puzzles',
    'Reading about art and music',
    'Working in teams',
    'Setting goals for myself and working to achieve them',
    'Organizing my desks, cupboards, bed etc',
    'Putting things together or assembling things',
    'Doing experiments',
    'Writing poetry, stories, articles, blogs and other creative compositions',
    'Teaching what I learn to others',
    'Persuading people',
    'Having clear instructions to follow to do work',
    'Taking care of pet animals',
    'Studying science',
    'Being creative in whatever I do',
    'Taking care of people who are ill at home',
    'Taking on new responsibilities',
    'Paying attention to details',
    'Working on outdoor jobs',
    'Figuring out how things work',
    'Playing musical instruments',
    'Learning about other cultures',
    'Starting my own business after I finish my education',
    'Keeping a well organised office',
    'Working on an offshore oil-drilling rig as an engineer',
    'Enjoying math and being good at it',
    'Acting in dramas and plays',
    'Helping people solve their problems',
    'Leading other people',
    'Keeping records of my work',
    'Assembling electronic parts on a circuit board to make a working amplifier',
    'Working with numbers and data',
    'Doing drawing and sketching',
    'Giving career guidance to people',
    'Giving speeches',
    'Using a computer program to generate customer bills',
    'Growing crops',
    'Studying the structure of the human body',
    'Conducting a musical choir',
    'Helping people with family-related problems',
    'Appointing dealers for my products for my business',
    'Generating the monthly payroll cheques for my office',
    'Planting and taking care of flowers & plants',
    'Developing a new medical treatment',
    'Writing the lyrics for a song',
    'Doing volunteer work at an NGO',
    'Doing a start-up',
    'Maintaining employee records',
    'Doing household repairs using tools',
    'Conducting research in social sciences ( History, Political Science, Sociology etc)',
    'Becoming an author of books',
    'Helping people overcome their addiction problems',
    'Managing a department within a company',
    'Computing and recording performance data for a company',
    'Doing camping, hiking, fishing and other adventure activities',
    'Studying human anatomy and diseases',
    'Producing designs from my own ideas',
    'Helping people with sports injuries recover',
    'Managing a team of people',
    'Planning how to get things done efficiently',
    'Operating machines and keep them in good condition',
    'Carrying out research projects on the subjects being studied',
    'Using my imagination in my work to make it better',
    'Helping people learn new skills',
    'Briefing people about a new product so that they buy it',
    'Making a market report for the management',
    'Repairing and fixing machines in a factory',
    'Studying established theories to arrive at their real life applications',
    'Expressing myself through paintings',
    'Working with community groups to solve problems of health, education, sanitation etc.',
    'Organising an exhibition to showcase the company\'s offerings',
    'Analysing statistical data to identify how well the company\'s products are doing',
    'Using hand/machine tools to make things that have utility at home',
    'Conducting research in new areas of science and technology as a career',
    'Leading creation of new products and solutions in my company',
    'Volunteering to help the elderly in the community with daily living activities',
    'Planing and overseeing the construction of a school',
    'Developing programs to control processing of metal or plastic parts by automatic machines',
    'Reading X-rays and ultra sound recordings',
    'Estimating damage to motor vehicles',
    'Photographing people or nature scenes',
    'Helping a patient regain mobility and relearn to walk',
    'Planning and coordinating activities for an event',
    'Inspecting buildings to detect fire hazards',
    'Fighting fires',
    'Solving problems by applying mathematical formulas or models',
    'Broadcasting the evening news',
    'Teaching in an school or college',
    'Coordinating the activities of employees in a bank branch',
    'Preparing tax returns for individuals or small businesses',
    'Getting the house painted and varnished',
    'Conducting diagnosis of the disease of a patient',
    'Creating computer games, videos or commercials using computers',
    'Counseling individuals to prevent mental health problems such as stress, anxiety etc.',
    'Overseeing the maintenance of a building',
    'Computing and recording financial information of an organisation correctly'
  ];
  
const options = [
    'If you strongly dislike doing/to do the activity mentioned in the statement',
    'If you dislike doing/to do the activity mentioned in the statement',
    'If you neither like nor dislike doing/to do the activity mentioned in the statement',
    'If you like doing/to do the activity mentioned in the statement',
    'If you strongly like doing/to do the activity mentioned in the statement'
  ];

  module.exports={originalQuestions}
